INSERT INTO VEICULO( ANO, COR, MARCA, MODELO, PLACA) VALUES ('2001', 'Preto', 'Chevrolet', 'Astra 2.0', 'HLP-2030');
INSERT INTO VEICULO( ANO, COR, MARCA, MODELO, PLACA) VALUES ('2020', 'Branco', 'Ford', 'Focus 2.0', 'QJG-2002');
INSERT INTO VEICULO( ANO, COR, MARCA, MODELO, PLACA) VALUES ('1999', 'Prata', 'Toyota', 'Corolla 1.8', 'KWK-1234');
INSERT INTO VEICULO( ANO, COR, MARCA, MODELO, PLACA) VALUES ('2011', 'Chumbo', 'Honda', 'Civic', 'EQK-1463');
INSERT INTO VEICULO( ANO, COR, MARCA, MODELO, PLACA) VALUES ('2006', 'Preto', 'Fiat', 'Uno 1.6 Mille', 'FMG-8888');





